'the search button'     : '.search_image'
'the search field'      : 'q'
'the username field'    : 'user_username'
'the password field'    : 'user_password'
'the login button'      : '#full-page-content input[type="submit"]'
'the Flash Error Message'   : '#flash-bad'
'the Flash Mask'		: '#exposeMask'
'the play button'       : 'play-button'
'the pause button'      : 'play-button'
'play'                  : 'play'
'pause'                 : 'pause'
'first explore'         : 'top_image_tag_1'